config/routes.rb
Rails.application.routes.draw do
    root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get 'users/sign_up', to: "users#new"
	post 'users', to: "users#create"
	resources :sessions, only: [:create, :destroy, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def destroy
		reset_session
    	redirect_to root_path
	end	

	def new
		@user = User.new
	end

	def create
		@user = User.find_by(email: params[:user][:email])
		if @user.nil?
			redirect_to users_sign_in_path, alert: 'Usuario no existe'
			return
		end

		if @user.password == params[:user][:password]
			session[:user_id] = @user.id
			redirect_to root_path
		else
			redirect_to users_sign_in_path, alert: 'Password inválido'
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
      	 	session[:user_id] = @user.id
      	 	redirect_to root_path
    	else
      		render :new
    	end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		User.find(session[:user_id])
	end

	def logged?
		session[:user_id].present? ? true : false
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'users/navbar' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/users/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "salir", session_path(current_user), method: :delete if logged?%>
      </li>
      <% unless logged?%>
      <li class="nav-item mx-3">
        <%= link_to "Sign_in", new_session_path %>
      </li>
      <li class="nav-item">
        <li><%= link_to "Sign_up", users_sign_up_path%></li>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/new.html.erb
<h3>Crea un nuevo usuario</h3>

<%= form_with(model: @user) do |form| %>

<div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, class: 'form-control' %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit "Ingresar", class: 'btn btn-primary' %>
  </div>

<% end %>